-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:bca58e41f23b0c1290e372b8c426a481:9883f088aac87c7035a0e5d0ebd15acd:8c471c90ed2f2eed613eeecf27e6bfdc$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "Bow.png",
				spriteColorRect = { x = 14, y = 0, width = 170, height = 62 },
				textureRect = { x = 1388, y = 2, width = 170, height = 62 },
				spriteSourceSize = { width = 200, height = 282 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death001.png",
				spriteColorRect = { x = 86, y = 48, width = 74, height = 100 },
				textureRect = { x = 400, y = 2, width = 74, height = 100 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death002.png",
				spriteColorRect = { x = 72, y = 30, width = 78, height = 118 },
				textureRect = { x = 206, y = 2, width = 78, height = 118 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death003.png",
				spriteColorRect = { x = 62, y = 30, width = 102, height = 118 },
				textureRect = { x = 102, y = 2, width = 102, height = 118 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death004.png",
				spriteColorRect = { x = 52, y = 28, width = 98, height = 120 },
				textureRect = { x = 2, y = 2, width = 98, height = 120 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death005.png",
				spriteColorRect = { x = 38, y = 34, width = 112, height = 114 },
				textureRect = { x = 286, y = 2, width = 112, height = 114 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death006.png",
				spriteColorRect = { x = 18, y = 52, width = 132, height = 96 },
				textureRect = { x = 546, y = 2, width = 132, height = 96 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death007.png",
				spriteColorRect = { x = 10, y = 64, width = 140, height = 84 },
				textureRect = { x = 1246, y = 2, width = 140, height = 84 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death008.png",
				spriteColorRect = { x = 46, y = 122, width = 104, height = 26 },
				textureRect = { x = 874, y = 96, width = 104, height = 26 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death009.png",
				spriteColorRect = { x = 46, y = 122, width = 104, height = 26 },
				textureRect = { x = 874, y = 96, width = 104, height = 26 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb001.png",
				spriteColorRect = { x = 62, y = 54, width = 56, height = 94 },
				textureRect = { x = 816, y = 2, width = 56, height = 94 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb002.png",
				spriteColorRect = { x = 54, y = 52, width = 66, height = 96 },
				textureRect = { x = 748, y = 2, width = 66, height = 96 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb003.png",
				spriteColorRect = { x = 54, y = 50, width = 68, height = 98 },
				textureRect = { x = 476, y = 2, width = 68, height = 98 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb004.png",
				spriteColorRect = { x = 52, y = 56, width = 76, height = 88 },
				textureRect = { x = 1168, y = 2, width = 76, height = 88 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb005.png",
				spriteColorRect = { x = 54, y = 58, width = 70, height = 90 },
				textureRect = { x = 1018, y = 2, width = 70, height = 90 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb006.png",
				spriteColorRect = { x = 58, y = 54, width = 66, height = 96 },
				textureRect = { x = 680, y = 2, width = 66, height = 96 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb007.png",
				spriteColorRect = { x = 56, y = 56, width = 68, height = 92 },
				textureRect = { x = 948, y = 2, width = 68, height = 92 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb008.png",
				spriteColorRect = { x = 52, y = 56, width = 76, height = 88 },
				textureRect = { x = 1090, y = 2, width = 76, height = 88 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb009.png",
				spriteColorRect = { x = 54, y = 56, width = 72, height = 92 },
				textureRect = { x = 874, y = 2, width = 72, height = 92 },
				spriteSourceSize = { width = 180, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

