-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:a3371dfd8e4d53cc01b67de064b87007:191c905b1c3a02e499f3972bd08109f9:50d79e8fef86c5a48888af9c8dae0e93$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "toad_animations_Green/Dust_0000",
				spriteColorRect = { x = 253, y = 166, width = 40, height = 36 },
				textureRect = { x = 448, y = 1866, width = 40, height = 36 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Dust_0001",
				spriteColorRect = { x = 262, y = 134, width = 28, height = 72 },
				textureRect = { x = 462, y = 486, width = 28, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Dust_0002",
				spriteColorRect = { x = 245, y = 116, width = 58, height = 80 },
				textureRect = { x = 166, y = 1944, width = 58, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Dust_0003",
				spriteColorRect = { x = 244, y = 114, width = 60, height = 76 },
				textureRect = { x = 324, y = 1098, width = 60, height = 76 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Dust_0004",
				spriteColorRect = { x = 243, y = 111, width = 62, height = 62 },
				textureRect = { x = 158, y = 1880, width = 62, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Dust_0005",
				spriteColorRect = { x = 246, y = 111, width = 56, height = 50 },
				textureRect = { x = 388, y = 1224, width = 56, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Dust_0006",
				spriteColorRect = { x = 249, y = 110, width = 50, height = 44 },
				textureRect = { x = 446, y = 1224, width = 50, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Dust_0007",
				spriteColorRect = { x = 252, y = 109, width = 42, height = 36 },
				textureRect = { x = 222, y = 1880, width = 42, height = 36 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Eat_0000",
				spriteColorRect = { x = 222, y = 145, width = 104, height = 62 },
				textureRect = { x = 160, y = 1816, width = 104, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Eat_0001",
				spriteColorRect = { x = 225, y = 117, width = 92, height = 92 },
				textureRect = { x = 320, y = 1392, width = 92, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Eat_0002",
				spriteColorRect = { x = 223, y = 124, width = 100, height = 84 },
				textureRect = { x = 280, y = 1570, width = 100, height = 84 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Eat_0003",
				spriteColorRect = { x = 222, y = 126, width = 102, height = 82 },
				textureRect = { x = 296, y = 1486, width = 102, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fall_0000",
				spriteColorRect = { x = 204, y = 136, width = 136, height = 66 },
				textureRect = { x = 324, y = 496, width = 136, height = 66 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fall_0001",
				spriteColorRect = { x = 233, y = 116, width = 84, height = 130 },
				textureRect = { x = 322, y = 1656, width = 84, height = 130 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fall_0002",
				spriteColorRect = { x = 245, y = 134, width = 70, height = 146 },
				textureRect = { x = 250, y = 1656, width = 70, height = 146 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fall_0003",
				spriteColorRect = { x = 258, y = 215, width = 46, height = 88 },
				textureRect = { x = 456, y = 396, width = 46, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_0000",
				spriteColorRect = { x = 213, y = 120, width = 136, height = 92 },
				textureRect = { x = 158, y = 1474, width = 136, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_0001",
				spriteColorRect = { x = 211, y = 106, width = 138, height = 108 },
				textureRect = { x = 156, y = 1282, width = 138, height = 108 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_0002",
				spriteColorRect = { x = 205, y = 116, width = 148, height = 98 },
				textureRect = { x = 306, y = 396, width = 148, height = 98 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_0003",
				spriteColorRect = { x = 208, y = 111, width = 144, height = 104 },
				textureRect = { x = 156, y = 1176, width = 144, height = 104 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Eat_0000",
				spriteColorRect = { x = 185, y = 113, width = 178, height = 94 },
				textureRect = { x = 176, y = 108, width = 178, height = 94 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Eat_0001",
				spriteColorRect = { x = 194, y = 79, width = 154, height = 124 },
				textureRect = { x = 2, y = 850, width = 154, height = 124 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Eat_0002",
				spriteColorRect = { x = 196, y = 75, width = 150, height = 132 },
				textureRect = { x = 358, y = 2, width = 150, height = 132 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Eat_0003",
				spriteColorRect = { x = 194, y = 75, width = 154, height = 132 },
				textureRect = { x = 2, y = 124, width = 154, height = 132 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Fall_0000",
				spriteColorRect = { x = 189, y = 100, width = 176, height = 106 },
				textureRect = { x = 122, y = 300, width = 176, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Fall_0001",
				spriteColorRect = { x = 201, y = 92, width = 154, height = 128 },
				textureRect = { x = 2, y = 720, width = 154, height = 128 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Fall_0002",
				spriteColorRect = { x = 222, y = 95, width = 118, height = 160 },
				textureRect = { x = 2, y = 426, width = 118, height = 160 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Fall_0003",
				spriteColorRect = { x = 235, y = 144, width = 88, height = 158 },
				textureRect = { x = 160, y = 1656, width = 88, height = 158 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Jump_0000",
				spriteColorRect = { x = 199, y = 128, width = 164, height = 86 },
				textureRect = { x = 344, y = 248, width = 164, height = 86 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Jump_0001",
				spriteColorRect = { x = 198, y = 122, width = 166, height = 94 },
				textureRect = { x = 156, y = 1080, width = 166, height = 94 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Jump_0002",
				spriteColorRect = { x = 215, y = 8, width = 118, height = 166 },
				textureRect = { x = 2, y = 258, width = 118, height = 166 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Jump_0003",
				spriteColorRect = { x = 208, y = 0, width = 154, height = 130 },
				textureRect = { x = 2, y = 588, width = 154, height = 130 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Jump_0004",
				spriteColorRect = { x = 209, y = 0, width = 152, height = 122 },
				textureRect = { x = 2, y = 1356, width = 152, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Jump_0005",
				spriteColorRect = { x = 209, y = 0, width = 152, height = 122 },
				textureRect = { x = 2, y = 1232, width = 152, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Jump_0006",
				spriteColorRect = { x = 209, y = 4, width = 152, height = 126 },
				textureRect = { x = 2, y = 1104, width = 152, height = 126 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Jump_0007",
				spriteColorRect = { x = 209, y = 56, width = 152, height = 126 },
				textureRect = { x = 2, y = 976, width = 152, height = 126 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0000",
				spriteColorRect = { x = 205, y = 87, width = 140, height = 124 },
				textureRect = { x = 2, y = 1596, width = 140, height = 124 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0001",
				spriteColorRect = { x = 155, y = 151, width = 206, height = 58 },
				textureRect = { x = 300, y = 336, width = 206, height = 58 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0002",
				spriteColorRect = { x = 160, y = 150, width = 200, height = 62 },
				textureRect = { x = 122, y = 508, width = 200, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0003",
				spriteColorRect = { x = 184, y = 113, width = 170, height = 98 },
				textureRect = { x = 158, y = 786, width = 170, height = 98 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0004",
				spriteColorRect = { x = 192, y = 94, width = 154, height = 114 },
				textureRect = { x = 2, y = 1480, width = 154, height = 114 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0005",
				spriteColorRect = { x = 189, y = 103, width = 162, height = 106 },
				textureRect = { x = 158, y = 572, width = 162, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0006",
				spriteColorRect = { x = 188, y = 113, width = 172, height = 96 },
				textureRect = { x = 158, y = 886, width = 172, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0007",
				spriteColorRect = { x = 191, y = 107, width = 168, height = 104 },
				textureRect = { x = 158, y = 680, width = 168, height = 104 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0008",
				spriteColorRect = { x = 194, y = 101, width = 156, height = 110 },
				textureRect = { x = 2, y = 1722, width = 156, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0009",
				spriteColorRect = { x = 197, y = 98, width = 154, height = 110 },
				textureRect = { x = 2, y = 1834, width = 154, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Land_0010",
				spriteColorRect = { x = 196, y = 100, width = 152, height = 110 },
				textureRect = { x = 356, y = 136, width = 152, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Run_0000",
				spriteColorRect = { x = 205, y = 114, width = 182, height = 98 },
				textureRect = { x = 122, y = 408, width = 182, height = 98 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Run_0001",
				spriteColorRect = { x = 205, y = 109, width = 180, height = 104 },
				textureRect = { x = 176, y = 2, width = 180, height = 104 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Run_0002",
				spriteColorRect = { x = 209, y = 93, width = 172, height = 120 },
				textureRect = { x = 2, y = 2, width = 172, height = 120 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Run_0003",
				spriteColorRect = { x = 206, y = 118, width = 182, height = 94 },
				textureRect = { x = 156, y = 984, width = 182, height = 94 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Fat_Run_0004",
				spriteColorRect = { x = 204, y = 120, width = 184, height = 94 },
				textureRect = { x = 158, y = 204, width = 184, height = 94 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Jump_0000",
				spriteColorRect = { x = 231, y = 75, width = 84, height = 104 },
				textureRect = { x = 302, y = 1176, width = 84, height = 104 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Jump_0001",
				spriteColorRect = { x = 246, y = 32, width = 76, height = 116 },
				textureRect = { x = 340, y = 980, width = 76, height = 116 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Jump_0002",
				spriteColorRect = { x = 249, y = 21, width = 90, height = 112 },
				textureRect = { x = 408, y = 1676, width = 90, height = 112 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Jump_0003",
				spriteColorRect = { x = 248, y = 21, width = 88, height = 110 },
				textureRect = { x = 418, y = 1040, width = 88, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Jump_0004",
				spriteColorRect = { x = 248, y = 25, width = 88, height = 110 },
				textureRect = { x = 412, y = 856, width = 88, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Jump_0005",
				spriteColorRect = { x = 248, y = 56, width = 88, height = 108 },
				textureRect = { x = 386, y = 1282, width = 88, height = 108 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Jump_0006",
				spriteColorRect = { x = 248, y = 100, width = 88, height = 108 },
				textureRect = { x = 296, y = 1282, width = 88, height = 108 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Run_0000",
				spriteColorRect = { x = 235, y = 136, width = 92, height = 68 },
				textureRect = { x = 414, y = 694, width = 92, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Run_0001",
				spriteColorRect = { x = 233, y = 140, width = 92, height = 66 },
				textureRect = { x = 266, y = 1886, width = 92, height = 66 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Run_0002",
				spriteColorRect = { x = 233, y = 134, width = 94, height = 72 },
				textureRect = { x = 414, y = 1392, width = 94, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Run_Land_0000",
				spriteColorRect = { x = 227, y = 149, width = 108, height = 56 },
				textureRect = { x = 400, y = 1486, width = 108, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Run_Land_0001",
				spriteColorRect = { x = 229, y = 146, width = 102, height = 60 },
				textureRect = { x = 322, y = 618, width = 102, height = 60 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0000",
				spriteColorRect = { x = 242, y = 107, width = 70, height = 100 },
				textureRect = { x = 330, y = 784, width = 70, height = 100 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0001",
				spriteColorRect = { x = 232, y = 104, width = 84, height = 102 },
				textureRect = { x = 328, y = 680, width = 84, height = 102 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0002",
				spriteColorRect = { x = 236, y = 113, width = 78, height = 92 },
				textureRect = { x = 332, y = 886, width = 78, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0003",
				spriteColorRect = { x = 237, y = 122, width = 76, height = 80 },
				textureRect = { x = 266, y = 1804, width = 76, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0004",
				spriteColorRect = { x = 215, y = 150, width = 116, height = 52 },
				textureRect = { x = 324, y = 564, width = 116, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0005",
				spriteColorRect = { x = 222, y = 151, width = 100, height = 54 },
				textureRect = { x = 408, y = 1620, width = 100, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0006",
				spriteColorRect = { x = 228, y = 139, width = 86, height = 66 },
				textureRect = { x = 360, y = 1866, width = 86, height = 66 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0007",
				spriteColorRect = { x = 237, y = 130, width = 70, height = 74 },
				textureRect = { x = 426, y = 1790, width = 70, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0008",
				spriteColorRect = { x = 233, y = 135, width = 90, height = 70 },
				textureRect = { x = 418, y = 968, width = 90, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0009",
				spriteColorRect = { x = 234, y = 133, width = 80, height = 74 },
				textureRect = { x = 344, y = 1790, width = 80, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0010",
				spriteColorRect = { x = 235, y = 136, width = 78, height = 72 },
				textureRect = { x = 314, y = 1954, width = 78, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0011",
				spriteColorRect = { x = 235, y = 135, width = 82, height = 74 },
				textureRect = { x = 426, y = 618, width = 82, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spin_0012",
				spriteColorRect = { x = 233, y = 135, width = 86, height = 72 },
				textureRect = { x = 226, y = 1954, width = 86, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spit_0000",
				spriteColorRect = { x = 213, y = 124, width = 120, height = 86 },
				textureRect = { x = 158, y = 1568, width = 120, height = 86 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spit_0001",
				spriteColorRect = { x = 211, y = 128, width = 162, height = 80 },
				textureRect = { x = 156, y = 1392, width = 162, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Spit_0002",
				spriteColorRect = { x = 212, y = 128, width = 162, height = 80 },
				textureRect = { x = 2, y = 1946, width = 162, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Toad_Skid_0000",
				spriteColorRect = { x = 222, y = 131, width = 100, height = 74 },
				textureRect = { x = 408, y = 1544, width = 100, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Toad_Skid_0001",
				spriteColorRect = { x = 221, y = 137, width = 106, height = 70 },
				textureRect = { x = 388, y = 1152, width = 106, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Green/Toad_Skid_0002",
				spriteColorRect = { x = 221, y = 136, width = 106, height = 70 },
				textureRect = { x = 402, y = 784, width = 106, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

