-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:8c352485b3b9a758e58a54729047dd1c:564641639235f1020547f8d72194391c:502b1574befcfed5a307619be5d7dc96$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "toad_animations_Pink/Dust_0000",
				spriteColorRect = { x = 253, y = 166, width = 40, height = 36 },
				textureRect = { x = 260, y = 458, width = 40, height = 36 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Dust_0001",
				spriteColorRect = { x = 262, y = 134, width = 28, height = 72 },
				textureRect = { x = 1628, y = 432, width = 28, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Dust_0002",
				spriteColorRect = { x = 245, y = 116, width = 58, height = 80 },
				textureRect = { x = 1756, y = 424, width = 58, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Dust_0003",
				spriteColorRect = { x = 244, y = 114, width = 60, height = 76 },
				textureRect = { x = 1168, y = 428, width = 60, height = 76 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Dust_0004",
				spriteColorRect = { x = 243, y = 111, width = 62, height = 62 },
				textureRect = { x = 460, y = 444, width = 62, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Dust_0005",
				spriteColorRect = { x = 246, y = 111, width = 56, height = 50 },
				textureRect = { x = 318, y = 456, width = 56, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Dust_0006",
				spriteColorRect = { x = 249, y = 110, width = 50, height = 44 },
				textureRect = { x = 164, y = 458, width = 50, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Dust_0007",
				spriteColorRect = { x = 252, y = 109, width = 42, height = 36 },
				textureRect = { x = 216, y = 458, width = 42, height = 36 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Eat_0000",
				spriteColorRect = { x = 222, y = 145, width = 104, height = 62 },
				textureRect = { x = 324, y = 264, width = 104, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Eat_0001",
				spriteColorRect = { x = 225, y = 117, width = 92, height = 92 },
				textureRect = { x = 1534, y = 2, width = 92, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Eat_0002",
				spriteColorRect = { x = 223, y = 124, width = 100, height = 84 },
				textureRect = { x = 1488, y = 194, width = 100, height = 84 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Eat_0003",
				spriteColorRect = { x = 222, y = 126, width = 102, height = 82 },
				textureRect = { x = 1574, y = 96, width = 102, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fall_0000",
				spriteColorRect = { x = 204, y = 136, width = 136, height = 66 },
				textureRect = { x = 946, y = 440, width = 136, height = 66 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fall_0001",
				spriteColorRect = { x = 233, y = 116, width = 84, height = 130 },
				textureRect = { x = 122, y = 134, width = 84, height = 130 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fall_0002",
				spriteColorRect = { x = 245, y = 134, width = 70, height = 146 },
				textureRect = { x = 92, y = 332, width = 70, height = 146 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fall_0003",
				spriteColorRect = { x = 258, y = 215, width = 46, height = 88 },
				textureRect = { x = 1414, y = 398, width = 46, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_0000",
				spriteColorRect = { x = 213, y = 120, width = 136, height = 92 },
				textureRect = { x = 1436, y = 100, width = 136, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_0001",
				spriteColorRect = { x = 211, y = 106, width = 138, height = 108 },
				textureRect = { x = 910, y = 2, width = 138, height = 108 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_0002",
				spriteColorRect = { x = 205, y = 116, width = 148, height = 98 },
				textureRect = { x = 1286, y = 108, width = 148, height = 98 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_0003",
				spriteColorRect = { x = 208, y = 111, width = 144, height = 104 },
				textureRect = { x = 1214, y = 2, width = 144, height = 104 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Fall_0000",
				spriteColorRect = { x = 189, y = 100, width = 176, height = 106 },
				textureRect = { x = 938, y = 112, width = 176, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Fall_0001",
				spriteColorRect = { x = 201, y = 92, width = 154, height = 128 },
				textureRect = { x = 208, y = 134, width = 154, height = 128 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Fall_0002",
				spriteColorRect = { x = 222, y = 95, width = 118, height = 160 },
				textureRect = { x = 2, y = 170, width = 118, height = 160 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Fall_0003",
				spriteColorRect = { x = 235, y = 144, width = 88, height = 158 },
				textureRect = { x = 2, y = 332, width = 88, height = 158 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Jump_0000",
				spriteColorRect = { x = 199, y = 128, width = 164, height = 86 },
				textureRect = { x = 1462, y = 398, width = 164, height = 86 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Jump_0001",
				spriteColorRect = { x = 198, y = 122, width = 166, height = 94 },
				textureRect = { x = 1320, y = 208, width = 166, height = 94 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Jump_0002",
				spriteColorRect = { x = 215, y = 8, width = 118, height = 166 },
				textureRect = { x = 2, y = 2, width = 118, height = 166 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Jump_0003",
				spriteColorRect = { x = 208, y = 0, width = 154, height = 130 },
				textureRect = { x = 122, y = 2, width = 154, height = 130 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Jump_0004",
				spriteColorRect = { x = 209, y = 0, width = 152, height = 122 },
				textureRect = { x = 432, y = 2, width = 152, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Jump_0005",
				spriteColorRect = { x = 209, y = 0, width = 152, height = 122 },
				textureRect = { x = 364, y = 130, width = 152, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Jump_0006",
				spriteColorRect = { x = 209, y = 4, width = 152, height = 126 },
				textureRect = { x = 164, y = 330, width = 152, height = 126 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Jump_0007",
				spriteColorRect = { x = 209, y = 56, width = 152, height = 126 },
				textureRect = { x = 278, y = 2, width = 152, height = 126 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0000",
				spriteColorRect = { x = 205, y = 87, width = 140, height = 124 },
				textureRect = { x = 318, y = 330, width = 140, height = 124 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0001",
				spriteColorRect = { x = 155, y = 151, width = 206, height = 58 },
				textureRect = { x = 628, y = 442, width = 206, height = 58 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0002",
				spriteColorRect = { x = 160, y = 150, width = 200, height = 62 },
				textureRect = { x = 122, y = 266, width = 200, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0003",
				spriteColorRect = { x = 184, y = 113, width = 170, height = 98 },
				textureRect = { x = 1148, y = 216, width = 170, height = 98 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0004",
				spriteColorRect = { x = 192, y = 94, width = 154, height = 114 },
				textureRect = { x = 664, y = 2, width = 154, height = 114 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0005",
				spriteColorRect = { x = 189, y = 103, width = 162, height = 106 },
				textureRect = { x = 1050, y = 2, width = 162, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0006",
				spriteColorRect = { x = 188, y = 113, width = 172, height = 96 },
				textureRect = { x = 1360, y = 2, width = 172, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0007",
				spriteColorRect = { x = 191, y = 107, width = 168, height = 104 },
				textureRect = { x = 1116, y = 110, width = 168, height = 104 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0008",
				spriteColorRect = { x = 194, y = 101, width = 156, height = 110 },
				textureRect = { x = 552, y = 330, width = 156, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0009",
				spriteColorRect = { x = 197, y = 98, width = 154, height = 110 },
				textureRect = { x = 692, y = 118, width = 154, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Land_0010",
				spriteColorRect = { x = 196, y = 100, width = 152, height = 110 },
				textureRect = { x = 710, y = 330, width = 152, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Run_0000",
				spriteColorRect = { x = 205, y = 114, width = 182, height = 98 },
				textureRect = { x = 696, y = 230, width = 182, height = 98 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Run_0001",
				spriteColorRect = { x = 205, y = 109, width = 180, height = 104 },
				textureRect = { x = 966, y = 220, width = 180, height = 104 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Run_0002",
				spriteColorRect = { x = 209, y = 93, width = 172, height = 120 },
				textureRect = { x = 518, y = 126, width = 172, height = 120 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Run_0003",
				spriteColorRect = { x = 206, y = 118, width = 182, height = 94 },
				textureRect = { x = 1230, y = 412, width = 182, height = 94 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Fat_Run_0004",
				spriteColorRect = { x = 204, y = 120, width = 184, height = 94 },
				textureRect = { x = 1202, y = 316, width = 184, height = 94 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Jump_0000",
				spriteColorRect = { x = 231, y = 75, width = 84, height = 104 },
				textureRect = { x = 1044, y = 326, width = 84, height = 104 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Jump_0001",
				spriteColorRect = { x = 246, y = 32, width = 76, height = 116 },
				textureRect = { x = 586, y = 2, width = 76, height = 116 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Jump_0002",
				spriteColorRect = { x = 249, y = 21, width = 90, height = 112 },
				textureRect = { x = 460, y = 330, width = 90, height = 112 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Jump_0003",
				spriteColorRect = { x = 248, y = 21, width = 88, height = 110 },
				textureRect = { x = 848, y = 114, width = 88, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Jump_0004",
				spriteColorRect = { x = 248, y = 25, width = 88, height = 110 },
				textureRect = { x = 820, y = 2, width = 88, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Jump_0005",
				spriteColorRect = { x = 248, y = 56, width = 88, height = 108 },
				textureRect = { x = 954, y = 330, width = 88, height = 108 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Jump_0006",
				spriteColorRect = { x = 248, y = 100, width = 88, height = 108 },
				textureRect = { x = 864, y = 330, width = 88, height = 108 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Run_0000",
				spriteColorRect = { x = 235, y = 136, width = 92, height = 68 },
				textureRect = { x = 1786, y = 218, width = 92, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Run_0001",
				spriteColorRect = { x = 233, y = 140, width = 92, height = 66 },
				textureRect = { x = 1590, y = 330, width = 92, height = 66 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Run_0002",
				spriteColorRect = { x = 233, y = 134, width = 94, height = 72 },
				textureRect = { x = 1786, y = 144, width = 94, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Run_Land_0000",
				spriteColorRect = { x = 227, y = 149, width = 108, height = 56 },
				textureRect = { x = 836, y = 442, width = 108, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Run_Land_0001",
				spriteColorRect = { x = 229, y = 146, width = 102, height = 60 },
				textureRect = { x = 524, y = 444, width = 102, height = 60 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0000",
				spriteColorRect = { x = 242, y = 107, width = 70, height = 100 },
				textureRect = { x = 1130, y = 326, width = 70, height = 100 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0001",
				spriteColorRect = { x = 232, y = 104, width = 84, height = 102 },
				textureRect = { x = 880, y = 226, width = 84, height = 102 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0002",
				spriteColorRect = { x = 236, y = 113, width = 78, height = 92 },
				textureRect = { x = 1388, y = 304, width = 78, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0003",
				spriteColorRect = { x = 237, y = 122, width = 76, height = 80 },
				textureRect = { x = 1776, y = 288, width = 76, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0004",
				spriteColorRect = { x = 215, y = 150, width = 116, height = 52 },
				textureRect = { x = 1756, y = 370, width = 116, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0005",
				spriteColorRect = { x = 222, y = 151, width = 100, height = 54 },
				textureRect = { x = 1672, y = 228, width = 100, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0006",
				spriteColorRect = { x = 228, y = 139, width = 86, height = 66 },
				textureRect = { x = 1792, y = 76, width = 86, height = 66 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0007",
				spriteColorRect = { x = 237, y = 130, width = 70, height = 74 },
				textureRect = { x = 1684, y = 356, width = 70, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0008",
				spriteColorRect = { x = 233, y = 135, width = 90, height = 70 },
				textureRect = { x = 1684, y = 284, width = 90, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0009",
				spriteColorRect = { x = 234, y = 133, width = 80, height = 74 },
				textureRect = { x = 1590, y = 180, width = 80, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0010",
				spriteColorRect = { x = 235, y = 136, width = 78, height = 72 },
				textureRect = { x = 1590, y = 256, width = 78, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0011",
				spriteColorRect = { x = 235, y = 135, width = 82, height = 74 },
				textureRect = { x = 1084, y = 432, width = 82, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spin_0012",
				spriteColorRect = { x = 233, y = 135, width = 86, height = 72 },
				textureRect = { x = 1792, y = 2, width = 86, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spit_0000",
				spriteColorRect = { x = 213, y = 124, width = 120, height = 86 },
				textureRect = { x = 1468, y = 304, width = 120, height = 86 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spit_0001",
				spriteColorRect = { x = 211, y = 128, width = 162, height = 80 },
				textureRect = { x = 1628, y = 2, width = 162, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Spit_0002",
				spriteColorRect = { x = 212, y = 128, width = 162, height = 80 },
				textureRect = { x = 532, y = 248, width = 162, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Toad_Skid_0000",
				spriteColorRect = { x = 222, y = 131, width = 100, height = 74 },
				textureRect = { x = 430, y = 254, width = 100, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Toad_Skid_0001",
				spriteColorRect = { x = 221, y = 137, width = 106, height = 70 },
				textureRect = { x = 1678, y = 156, width = 106, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations_Pink/Toad_Skid_0002",
				spriteColorRect = { x = 221, y = 136, width = 106, height = 70 },
				textureRect = { x = 1678, y = 84, width = 106, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

