-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:22d6c4b331628f8cb79e8690b34f9e4a:14d26d33f676b66ea082c8b3c3e65253:e467976e2aa514ddf0dc33c8c495c2ff$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "icetile2/TileBreak_0000",
				spriteColorRect = { x = 0, y = 12, width = 194, height = 194 },
				textureRect = { x = 2, y = 2, width = 194, height = 194 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0001",
				spriteColorRect = { x = 0, y = 38, width = 188, height = 136 },
				textureRect = { x = 196, y = 316, width = 188, height = 136 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0002",
				spriteColorRect = { x = 0, y = 56, width = 186, height = 104 },
				textureRect = { x = 2, y = 376, width = 186, height = 104 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0003",
				spriteColorRect = { x = 1, y = 72, width = 134, height = 88 },
				textureRect = { x = 926, y = 338, width = 134, height = 88 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0004",
				spriteColorRect = { x = 1, y = 106, width = 150, height = 54 },
				textureRect = { x = 752, y = 442, width = 150, height = 54 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0005",
				spriteColorRect = { x = 0, y = 114, width = 150, height = 46 },
				textureRect = { x = 572, y = 448, width = 150, height = 46 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0006",
				spriteColorRect = { x = 0, y = 115, width = 154, height = 60 },
				textureRect = { x = 926, y = 432, width = 154, height = 60 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0000",
				spriteColorRect = { x = 0, y = 72, width = 172, height = 102 },
				textureRect = { x = 752, y = 338, width = 172, height = 102 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0001",
				spriteColorRect = { x = 0, y = 73, width = 178, height = 112 },
				textureRect = { x = 572, y = 334, width = 178, height = 112 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0002",
				spriteColorRect = { x = 0, y = 72, width = 184, height = 124 },
				textureRect = { x = 386, y = 330, width = 184, height = 124 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0003",
				spriteColorRect = { x = 0, y = 67, width = 192, height = 140 },
				textureRect = { x = 198, y = 174, width = 192, height = 140 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0004",
				spriteColorRect = { x = 1, y = 53, width = 192, height = 158 },
				textureRect = { x = 392, y = 170, width = 192, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0005",
				spriteColorRect = { x = 1, y = 35, width = 192, height = 176 },
				textureRect = { x = 2, y = 198, width = 192, height = 176 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0006",
				spriteColorRect = { x = 1, y = 41, width = 192, height = 170 },
				textureRect = { x = 198, y = 2, width = 192, height = 170 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0007",
				spriteColorRect = { x = 1, y = 45, width = 192, height = 166 },
				textureRect = { x = 974, y = 170, width = 192, height = 166 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0008",
				spriteColorRect = { x = 1, y = 49, width = 192, height = 162 },
				textureRect = { x = 586, y = 170, width = 192, height = 162 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0009",
				spriteColorRect = { x = 1, y = 45, width = 192, height = 166 },
				textureRect = { x = 780, y = 170, width = 192, height = 166 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0010",
				spriteColorRect = { x = 1, y = 45, width = 192, height = 166 },
				textureRect = { x = 780, y = 170, width = 192, height = 166 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0000",
				spriteColorRect = { x = 1, y = 45, width = 192, height = 166 },
				textureRect = { x = 974, y = 2, width = 192, height = 166 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0001",
				spriteColorRect = { x = 1, y = 45, width = 192, height = 166 },
				textureRect = { x = 780, y = 2, width = 192, height = 166 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0002",
				spriteColorRect = { x = 1, y = 45, width = 192, height = 166 },
				textureRect = { x = 586, y = 2, width = 192, height = 166 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0003",
				spriteColorRect = { x = 1, y = 45, width = 192, height = 166 },
				textureRect = { x = 392, y = 2, width = 192, height = 166 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mockup_toad_new/Shadow_0000",
				spriteColorRect = { x = 206, y = 227, width = 138, height = 24 },
				textureRect = { x = 190, y = 454, width = 138, height = 24 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mockup_toad_new/ToadIdle_0000",
				spriteColorRect = { x = 216, y = 154, width = 116, height = 92 },
				textureRect = { x = 1062, y = 338, width = 116, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

