-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:d5187ed4b27749ea81aaddcb783a296e:390511715b52d307ab4e55e74d505984:e467976e2aa514ddf0dc33c8c495c2ff$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "food/Item_0000",
				spriteColorRect = { x = 66, y = 81, width = 118, height = 92 },
				textureRect = { x = 2, y = 638, width = 118, height = 92 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Item_0001",
				spriteColorRect = { x = 62, y = 67, width = 104, height = 116 },
				textureRect = { x = 1734, y = 618, width = 104, height = 116 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Item_0002",
				spriteColorRect = { x = 62, y = 83, width = 120, height = 90 },
				textureRect = { x = 1622, y = 402, width = 120, height = 90 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/Blank_0000",
				spriteColorRect = { x = 98, y = 158, width = 2, height = 2 },
				textureRect = { x = 946, y = 326, width = 2, height = 2 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0000",
				spriteColorRect = { x = 62, y = 12, width = 132, height = 244 },
				textureRect = { x = 674, y = 136, width = 132, height = 244 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0001",
				spriteColorRect = { x = 64, y = 38, width = 126, height = 192 },
				textureRect = { x = 136, y = 554, width = 126, height = 192 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0002",
				spriteColorRect = { x = 62, y = 56, width = 134, height = 174 },
				textureRect = { x = 704, y = 570, width = 134, height = 174 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0003",
				spriteColorRect = { x = 92, y = 72, width = 68, height = 88 },
				textureRect = { x = 972, y = 658, width = 68, height = 88 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0004",
				spriteColorRect = { x = 82, y = 106, width = 84, height = 54 },
				textureRect = { x = 1832, y = 522, width = 84, height = 54 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0005",
				spriteColorRect = { x = 96, y = 114, width = 54, height = 46 },
				textureRect = { x = 1042, y = 696, width = 54, height = 46 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0000",
				spriteColorRect = { x = 92, y = 119, width = 62, height = 56 },
				textureRect = { x = 1840, y = 686, width = 62, height = 56 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0001",
				spriteColorRect = { x = 82, y = 72, width = 90, height = 102 },
				textureRect = { x = 1940, y = 620, width = 90, height = 102 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0002",
				spriteColorRect = { x = 76, y = 73, width = 102, height = 112 },
				textureRect = { x = 1832, y = 408, width = 102, height = 112 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0003",
				spriteColorRect = { x = 61, y = 73, width = 130, height = 136 },
				textureRect = { x = 1686, y = 140, width = 130, height = 136 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0004",
				spriteColorRect = { x = 59, y = 68, width = 134, height = 152 },
				textureRect = { x = 1082, y = 516, width = 134, height = 152 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0005",
				spriteColorRect = { x = 56, y = 54, width = 138, height = 182 },
				textureRect = { x = 946, y = 330, width = 138, height = 182 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0006",
				spriteColorRect = { x = 57, y = 39, width = 140, height = 202 },
				textureRect = { x = 808, y = 122, width = 140, height = 202 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0007",
				spriteColorRect = { x = 63, y = 41, width = 130, height = 198 },
				textureRect = { x = 412, y = 542, width = 130, height = 198 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0008",
				spriteColorRect = { x = 61, y = 46, width = 132, height = 180 },
				textureRect = { x = 1218, y = 490, width = 132, height = 180 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0009",
				spriteColorRect = { x = 63, y = 49, width = 130, height = 178 },
				textureRect = { x = 1484, y = 490, width = 130, height = 178 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0010",
				spriteColorRect = { x = 63, y = 46, width = 130, height = 184 },
				textureRect = { x = 1490, y = 302, width = 130, height = 184 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0011",
				spriteColorRect = { x = 61, y = 45, width = 132, height = 186 },
				textureRect = { x = 812, y = 326, width = 132, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRipple_0000",
				spriteColorRect = { x = 62, y = 45, width = 132, height = 186 },
				textureRect = { x = 678, y = 382, width = 132, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRipple_0001",
				spriteColorRect = { x = 61, y = 45, width = 132, height = 186 },
				textureRect = { x = 544, y = 446, width = 132, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRipple_0002",
				spriteColorRect = { x = 55, y = 45, width = 138, height = 186 },
				textureRect = { x = 1218, y = 302, width = 138, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0000",
				spriteColorRect = { x = 63, y = 45, width = 130, height = 186 },
				textureRect = { x = 1352, y = 490, width = 130, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0001",
				spriteColorRect = { x = 63, y = 45, width = 130, height = 186 },
				textureRect = { x = 840, y = 514, width = 130, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0002",
				spriteColorRect = { x = 63, y = 45, width = 130, height = 186 },
				textureRect = { x = 1358, y = 302, width = 130, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0003",
				spriteColorRect = { x = 63, y = 46, width = 130, height = 184 },
				textureRect = { x = 1086, y = 330, width = 130, height = 184 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mockup_toad_new/Shadow_0000",
				spriteColorRect = { x = 206, y = 227, width = 138, height = 24 },
				textureRect = { x = 1042, y = 670, width = 138, height = 24 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mockup_toad_new/ToadIdle_0000",
				spriteColorRect = { x = 216, y = 154, width = 116, height = 92 },
				textureRect = { x = 1616, y = 618, width = 116, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0000",
				spriteColorRect = { x = 55, y = 37, width = 146, height = 186 },
				textureRect = { x = 264, y = 554, width = 146, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0001",
				spriteColorRect = { x = 30, y = 0, width = 210, height = 240 },
				textureRect = { x = 136, y = 2, width = 210, height = 240 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0002",
				spriteColorRect = { x = 39, y = 0, width = 170, height = 228 },
				textureRect = { x = 348, y = 2, width = 170, height = 228 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0003",
				spriteColorRect = { x = 40, y = 45, width = 182, height = 176 },
				textureRect = { x = 950, y = 152, width = 182, height = 176 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0004",
				spriteColorRect = { x = 22, y = 106, width = 208, height = 118 },
				textureRect = { x = 752, y = 2, width = 208, height = 118 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0005",
				spriteColorRect = { x = 0, y = 97, width = 230, height = 132 },
				textureRect = { x = 520, y = 2, width = 230, height = 132 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0006",
				spriteColorRect = { x = 31, y = 95, width = 158, height = 112 },
				textureRect = { x = 544, y = 634, width = 158, height = 112 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0007",
				spriteColorRect = { x = 79, y = 126, width = 66, height = 34 },
				textureRect = { x = 1730, y = 358, width = 66, height = 34 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0008",
				spriteColorRect = { x = 69, y = 124, width = 90, height = 36 },
				textureRect = { x = 840, y = 702, width = 90, height = 36 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStatue_0000",
				spriteColorRect = { x = 62, y = 145, width = 132, height = 322 },
				textureRect = { x = 2, y = 2, width = 132, height = 322 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStatue_0001",
				spriteColorRect = { x = 62, y = 159, width = 132, height = 308 },
				textureRect = { x = 540, y = 136, width = 132, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStatue_0002",
				spriteColorRect = { x = 62, y = 157, width = 132, height = 310 },
				textureRect = { x = 2, y = 326, width = 132, height = 310 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStone_0000",
				spriteColorRect = { x = 62, y = 159, width = 132, height = 308 },
				textureRect = { x = 406, y = 232, width = 132, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStone_0001",
				spriteColorRect = { x = 61, y = 159, width = 134, height = 308 },
				textureRect = { x = 136, y = 244, width = 134, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStone_0002",
				spriteColorRect = { x = 62, y = 159, width = 132, height = 308 },
				textureRect = { x = 272, y = 244, width = 132, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Eat_0000",
				spriteColorRect = { x = 221, y = 117, width = 106, height = 122 },
				textureRect = { x = 1724, y = 494, width = 106, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Eat_0001",
				spriteColorRect = { x = 221, y = 117, width = 106, height = 122 },
				textureRect = { x = 1810, y = 284, width = 106, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Eat_0002",
				spriteColorRect = { x = 221, y = 117, width = 106, height = 122 },
				textureRect = { x = 1616, y = 494, width = 106, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Eat_0003",
				spriteColorRect = { x = 221, y = 117, width = 106, height = 122 },
				textureRect = { x = 1622, y = 278, width = 106, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_0000",
				spriteColorRect = { x = 202, y = 103, width = 158, height = 136 },
				textureRect = { x = 1526, y = 140, width = 158, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_0001",
				spriteColorRect = { x = 202, y = 103, width = 158, height = 136 },
				textureRect = { x = 1846, y = 2, width = 158, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_0002",
				spriteColorRect = { x = 202, y = 103, width = 158, height = 136 },
				textureRect = { x = 1686, y = 2, width = 158, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_0003",
				spriteColorRect = { x = 202, y = 103, width = 158, height = 136 },
				textureRect = { x = 1526, y = 2, width = 158, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0000",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 1322, y = 152, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0001",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 1338, y = 2, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0002",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 1134, y = 152, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0003",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 1150, y = 2, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0004",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 962, y = 2, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0005",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0006",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0007",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0008",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0009",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0010",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0011",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0012",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0013",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0014",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0015",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0016",
				spriteColorRect = { x = 236, y = 161, width = 78, height = 78 },
				textureRect = { x = 1730, y = 278, width = 78, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0000",
				spriteColorRect = { x = 230, y = 121, width = 98, height = 118 },
				textureRect = { x = 1918, y = 284, width = 98, height = 118 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0001",
				spriteColorRect = { x = 230, y = 105, width = 98, height = 134 },
				textureRect = { x = 1926, y = 140, width = 98, height = 134 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0002",
				spriteColorRect = { x = 230, y = 97, width = 108, height = 142 },
				textureRect = { x = 972, y = 514, width = 108, height = 142 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0003",
				spriteColorRect = { x = 230, y = 97, width = 106, height = 142 },
				textureRect = { x = 1818, y = 140, width = 106, height = 142 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Run_0000",
				spriteColorRect = { x = 230, y = 133, width = 98, height = 106 },
				textureRect = { x = 1940, y = 512, width = 98, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Run_0001",
				spriteColorRect = { x = 230, y = 133, width = 98, height = 106 },
				textureRect = { x = 1840, y = 578, width = 98, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Run_0002",
				spriteColorRect = { x = 230, y = 133, width = 98, height = 106 },
				textureRect = { x = 1936, y = 404, width = 98, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

