-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:e0d4f9972487f796b9a07e33a74c6862:18a6ac90fa0a95da32e1bad650488897:e467976e2aa514ddf0dc33c8c495c2ff$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "food/Chicken_0000",
				spriteColorRect = { x = 64, y = 81, width = 130, height = 102 },
				textureRect = { x = 418, y = 1124, width = 130, height = 102 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Chicken_0001",
				spriteColorRect = { x = 62, y = 63, width = 128, height = 120 },
				textureRect = { x = 1228, y = 1878, width = 128, height = 120 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Chicken_0002",
				spriteColorRect = { x = 64, y = 71, width = 130, height = 112 },
				textureRect = { x = 1244, y = 866, width = 130, height = 112 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Chicken_0003",
				spriteColorRect = { x = 61, y = 69, width = 128, height = 114 },
				textureRect = { x = 1250, y = 980, width = 128, height = 114 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Droplet_0000",
				spriteColorRect = { x = 87, y = 83, width = 82, height = 86 },
				textureRect = { x = 1338, y = 1464, width = 82, height = 86 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Droplet_0001",
				spriteColorRect = { x = 87, y = 83, width = 82, height = 86 },
				textureRect = { x = 1376, y = 880, width = 82, height = 86 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Droplet_0002",
				spriteColorRect = { x = 87, y = 83, width = 82, height = 86 },
				textureRect = { x = 406, y = 532, width = 82, height = 86 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Droplet_0003",
				spriteColorRect = { x = 66, y = 59, width = 122, height = 108 },
				textureRect = { x = 1338, y = 714, width = 122, height = 108 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Droplet_0004",
				spriteColorRect = { x = 50, y = 57, width = 156, height = 108 },
				textureRect = { x = 270, y = 826, width = 156, height = 108 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Droplet_0005",
				spriteColorRect = { x = 46, y = 69, width = 154, height = 100 },
				textureRect = { x = 262, y = 1128, width = 154, height = 100 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Ham_0000",
				spriteColorRect = { x = 61, y = 67, width = 112, height = 126 },
				textureRect = { x = 428, y = 808, width = 112, height = 126 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Ham_0001",
				spriteColorRect = { x = 61, y = 53, width = 112, height = 140 },
				textureRect = { x = 848, y = 1056, width = 112, height = 140 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Ham_0002",
				spriteColorRect = { x = 61, y = 57, width = 112, height = 136 },
				textureRect = { x = 858, y = 1198, width = 112, height = 136 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Ham_0003",
				spriteColorRect = { x = 61, y = 61, width = 112, height = 132 },
				textureRect = { x = 1276, y = 1732, width = 112, height = 132 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Ribs_0000",
				spriteColorRect = { x = 49, y = 76, width = 148, height = 114 },
				textureRect = { x = 1094, y = 1232, width = 148, height = 114 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Ribs_0001",
				spriteColorRect = { x = 46, y = 66, width = 150, height = 124 },
				textureRect = { x = 1304, y = 438, width = 150, height = 124 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Ribs_0002",
				spriteColorRect = { x = 49, y = 70, width = 148, height = 120 },
				textureRect = { x = 1094, y = 1348, width = 148, height = 120 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Ribs_0003",
				spriteColorRect = { x = 51, y = 68, width = 146, height = 122 },
				textureRect = { x = 1082, y = 1470, width = 146, height = 122 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Shadow_0000",
				spriteColorRect = { x = 99, y = 136, width = 34, height = 24 },
				textureRect = { x = 136, y = 1168, width = 34, height = 24 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Shadow_0001",
				spriteColorRect = { x = 99, y = 132, width = 42, height = 28 },
				textureRect = { x = 218, y = 1762, width = 42, height = 28 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "food/Shadow_0002",
				spriteColorRect = { x = 79, y = 101, width = 90, height = 68 },
				textureRect = { x = 264, y = 1950, width = 90, height = 68 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/Blank_0000",
				spriteColorRect = { x = 98, y = 158, width = 2, height = 2 },
				textureRect = { x = 382, y = 1578, width = 2, height = 2 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0000",
				spriteColorRect = { x = 62, y = 12, width = 132, height = 244 },
				textureRect = { x = 2, y = 948, width = 132, height = 244 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0001",
				spriteColorRect = { x = 64, y = 38, width = 126, height = 192 },
				textureRect = { x = 2, y = 1836, width = 126, height = 192 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0002",
				spriteColorRect = { x = 62, y = 56, width = 134, height = 174 },
				textureRect = { x = 288, y = 1230, width = 134, height = 174 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0003",
				spriteColorRect = { x = 92, y = 72, width = 68, height = 88 },
				textureRect = { x = 1388, y = 46, width = 68, height = 88 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0004",
				spriteColorRect = { x = 82, y = 106, width = 84, height = 54 },
				textureRect = { x = 1376, y = 824, width = 84, height = 54 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileBreak_0005",
				spriteColorRect = { x = 96, y = 114, width = 54, height = 46 },
				textureRect = { x = 1230, y = 2000, width = 54, height = 46 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0000",
				spriteColorRect = { x = 92, y = 119, width = 62, height = 56 },
				textureRect = { x = 1082, y = 1990, width = 62, height = 56 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0001",
				spriteColorRect = { x = 82, y = 72, width = 90, height = 102 },
				textureRect = { x = 1368, y = 1096, width = 90, height = 102 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0002",
				spriteColorRect = { x = 76, y = 73, width = 102, height = 112 },
				textureRect = { x = 1358, y = 1866, width = 102, height = 112 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0003",
				spriteColorRect = { x = 61, y = 73, width = 130, height = 136 },
				textureRect = { x = 828, y = 1902, width = 130, height = 136 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0004",
				spriteColorRect = { x = 59, y = 68, width = 134, height = 152 },
				textureRect = { x = 552, y = 1058, width = 134, height = 152 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0005",
				spriteColorRect = { x = 56, y = 54, width = 138, height = 182 },
				textureRect = { x = 552, y = 874, width = 138, height = 182 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0006",
				spriteColorRect = { x = 57, y = 39, width = 140, height = 202 },
				textureRect = { x = 270, y = 622, width = 140, height = 202 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0007",
				spriteColorRect = { x = 63, y = 41, width = 130, height = 198 },
				textureRect = { x = 2, y = 1194, width = 130, height = 198 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0008",
				spriteColorRect = { x = 61, y = 46, width = 132, height = 180 },
				textureRect = { x = 564, y = 1212, width = 132, height = 180 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0009",
				spriteColorRect = { x = 63, y = 49, width = 130, height = 178 },
				textureRect = { x = 554, y = 1578, width = 130, height = 178 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0010",
				spriteColorRect = { x = 63, y = 46, width = 130, height = 184 },
				textureRect = { x = 824, y = 870, width = 130, height = 184 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRespawn_0011",
				spriteColorRect = { x = 61, y = 45, width = 132, height = 186 },
				textureRect = { x = 264, y = 1762, width = 132, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRipple_0000",
				spriteColorRect = { x = 62, y = 45, width = 132, height = 186 },
				textureRect = { x = 418, y = 936, width = 132, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRipple_0001",
				spriteColorRect = { x = 61, y = 45, width = 132, height = 186 },
				textureRect = { x = 130, y = 1792, width = 132, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileRipple_0002",
				spriteColorRect = { x = 55, y = 45, width = 138, height = 186 },
				textureRect = { x = 398, y = 1758, width = 138, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0000",
				spriteColorRect = { x = 63, y = 45, width = 130, height = 186 },
				textureRect = { x = 412, y = 620, width = 130, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0001",
				spriteColorRect = { x = 63, y = 45, width = 130, height = 186 },
				textureRect = { x = 670, y = 1758, width = 130, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0002",
				spriteColorRect = { x = 63, y = 45, width = 130, height = 186 },
				textureRect = { x = 538, y = 1758, width = 130, height = 186 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icetile2/TileState_0003",
				spriteColorRect = { x = 63, y = 46, width = 130, height = 184 },
				textureRect = { x = 692, y = 874, width = 130, height = 184 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mockup_toad_new/Shadow_0000",
				spriteColorRect = { x = 206, y = 227, width = 138, height = 24 },
				textureRect = { x = 954, y = 1416, width = 138, height = 24 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mockup_toad_new/ToadIdle_0000",
				spriteColorRect = { x = 216, y = 154, width = 116, height = 92 },
				textureRect = { x = 710, y = 1946, width = 116, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0000",
				spriteColorRect = { x = 38, y = 41, width = 52, height = 66 },
				textureRect = { x = 490, y = 542, width = 52, height = 66 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0001",
				spriteColorRect = { x = 30, y = 13, width = 74, height = 100 },
				textureRect = { x = 634, y = 1946, width = 74, height = 100 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0002",
				spriteColorRect = { x = 33, y = 13, width = 60, height = 96 },
				textureRect = { x = 1388, y = 136, width = 60, height = 96 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0003",
				spriteColorRect = { x = 32, y = 44, width = 66, height = 62 },
				textureRect = { x = 1380, y = 968, width = 66, height = 62 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0004",
				spriteColorRect = { x = 28, y = 65, width = 72, height = 42 },
				textureRect = { x = 1388, y = 2, width = 72, height = 42 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0005",
				spriteColorRect = { x = 18, y = 63, width = 82, height = 46 },
				textureRect = { x = 1146, y = 2000, width = 82, height = 46 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0006",
				spriteColorRect = { x = 30, y = 61, width = 56, height = 40 },
				textureRect = { x = 1338, y = 1552, width = 56, height = 40 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0007",
				spriteColorRect = { x = 47, y = 72, width = 24, height = 10 },
				textureRect = { x = 566, y = 1566, width = 24, height = 10 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spash/Splash_0008",
				spriteColorRect = { x = 44, y = 72, width = 32, height = 10 },
				textureRect = { x = 204, y = 1394, width = 32, height = 10 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/Pillar_0000",
				spriteColorRect = { x = 62, y = 159, width = 132, height = 308 },
				textureRect = { x = 406, y = 2, width = 132, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/Pillar_0001",
				spriteColorRect = { x = 62, y = 159, width = 132, height = 308 },
				textureRect = { x = 272, y = 312, width = 132, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/Pillar_0002",
				spriteColorRect = { x = 61, y = 159, width = 134, height = 308 },
				textureRect = { x = 136, y = 312, width = 134, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStatue_0000",
				spriteColorRect = { x = 62, y = 145, width = 132, height = 322 },
				textureRect = { x = 2, y = 2, width = 132, height = 322 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStatue_0001",
				spriteColorRect = { x = 62, y = 159, width = 132, height = 308 },
				textureRect = { x = 136, y = 622, width = 132, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStatue_0002",
				spriteColorRect = { x = 62, y = 157, width = 132, height = 310 },
				textureRect = { x = 2, y = 326, width = 132, height = 310 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStone_0000",
				spriteColorRect = { x = 62, y = 159, width = 132, height = 308 },
				textureRect = { x = 2, y = 638, width = 132, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStone_0001",
				spriteColorRect = { x = 61, y = 159, width = 134, height = 308 },
				textureRect = { x = 136, y = 2, width = 134, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stonetile2/TileStone_0002",
				spriteColorRect = { x = 62, y = 159, width = 132, height = 308 },
				textureRect = { x = 272, y = 2, width = 132, height = 308 },
				spriteSourceSize = { width = 256, height = 512 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Eat_0000",
				spriteColorRect = { x = 221, y = 117, width = 106, height = 122 },
				textureRect = { x = 1352, y = 1220, width = 106, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Eat_0001",
				spriteColorRect = { x = 221, y = 117, width = 106, height = 122 },
				textureRect = { x = 1244, y = 1232, width = 106, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Eat_0002",
				spriteColorRect = { x = 221, y = 117, width = 106, height = 122 },
				textureRect = { x = 1260, y = 1096, width = 106, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Eat_0003",
				spriteColorRect = { x = 221, y = 117, width = 106, height = 122 },
				textureRect = { x = 1230, y = 1470, width = 106, height = 122 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fall_0000",
				spriteColorRect = { x = 201, y = 129, width = 144, height = 110 },
				textureRect = { x = 1082, y = 1878, width = 144, height = 110 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fall_0001",
				spriteColorRect = { x = 218, y = 115, width = 114, height = 136 },
				textureRect = { x = 1260, y = 1594, width = 114, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fall_0002",
				spriteColorRect = { x = 185, y = 100, width = 138, height = 182 },
				textureRect = { x = 424, y = 1228, width = 138, height = 182 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fall_0003",
				spriteColorRect = { x = 235, y = 160, width = 84, height = 144 },
				textureRect = { x = 686, y = 1612, width = 84, height = 144 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_0000",
				spriteColorRect = { x = 202, y = 103, width = 158, height = 136 },
				textureRect = { x = 700, y = 1474, width = 158, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_0001",
				spriteColorRect = { x = 202, y = 103, width = 158, height = 136 },
				textureRect = { x = 700, y = 1336, width = 158, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_0002",
				spriteColorRect = { x = 202, y = 103, width = 158, height = 136 },
				textureRect = { x = 698, y = 1198, width = 158, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_0003",
				spriteColorRect = { x = 202, y = 103, width = 158, height = 136 },
				textureRect = { x = 688, y = 1060, width = 158, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Eat_0000",
				spriteColorRect = { x = 177, y = 97, width = 190, height = 142 },
				textureRect = { x = 742, y = 244, width = 190, height = 142 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Eat_0001",
				spriteColorRect = { x = 186, y = 65, width = 176, height = 174 },
				textureRect = { x = 204, y = 1406, width = 176, height = 174 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Eat_0002",
				spriteColorRect = { x = 192, y = 61, width = 166, height = 178 },
				textureRect = { x = 386, y = 1578, width = 166, height = 178 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Eat_0003",
				spriteColorRect = { x = 192, y = 61, width = 166, height = 178 },
				textureRect = { x = 218, y = 1582, width = 166, height = 178 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Fall_0000",
				spriteColorRect = { x = 185, y = 95, width = 184, height = 144 },
				textureRect = { x = 1118, y = 416, width = 184, height = 144 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Fall_0001",
				spriteColorRect = { x = 193, y = 91, width = 172, height = 148 },
				textureRect = { x = 1280, y = 564, width = 172, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Fall_0002",
				spriteColorRect = { x = 205, y = 91, width = 150, height = 170 },
				textureRect = { x = 1310, y = 266, width = 150, height = 170 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Fall_0003",
				spriteColorRect = { x = 214, y = 133, width = 132, height = 170 },
				textureRect = { x = 566, y = 1394, width = 132, height = 170 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Jump_0000",
				spriteColorRect = { x = 196, y = 103, width = 170, height = 136 },
				textureRect = { x = 1084, y = 728, width = 170, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Jump_0001",
				spriteColorRect = { x = 196, y = 103, width = 170, height = 136 },
				textureRect = { x = 912, y = 710, width = 170, height = 136 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Jump_0002",
				spriteColorRect = { x = 216, y = 5, width = 124, height = 234 },
				textureRect = { x = 136, y = 932, width = 124, height = 234 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Jump_0003",
				spriteColorRect = { x = 207, y = 0, width = 154, height = 240 },
				textureRect = { x = 1008, y = 2, width = 154, height = 240 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Jump_0004",
				spriteColorRect = { x = 207, y = 0, width = 154, height = 240 },
				textureRect = { x = 852, y = 2, width = 154, height = 240 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Jump_0005",
				spriteColorRect = { x = 207, y = 0, width = 154, height = 240 },
				textureRect = { x = 696, y = 2, width = 154, height = 240 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Jump_0006",
				spriteColorRect = { x = 207, y = 0, width = 154, height = 240 },
				textureRect = { x = 540, y = 2, width = 154, height = 240 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Jump_0007",
				spriteColorRect = { x = 207, y = 49, width = 154, height = 190 },
				textureRect = { x = 262, y = 936, width = 154, height = 190 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0000",
				spriteColorRect = { x = 196, y = 77, width = 152, height = 162 },
				textureRect = { x = 134, y = 1230, width = 152, height = 162 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0001",
				spriteColorRect = { x = 147, y = 109, width = 222, height = 130 },
				textureRect = { x = 1164, y = 134, width = 222, height = 130 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0002",
				spriteColorRect = { x = 147, y = 109, width = 222, height = 130 },
				textureRect = { x = 1164, y = 2, width = 222, height = 130 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0003",
				spriteColorRect = { x = 169, y = 93, width = 200, height = 146 },
				textureRect = { x = 540, y = 244, width = 200, height = 146 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0004",
				spriteColorRect = { x = 180, y = 75, width = 182, height = 164 },
				textureRect = { x = 728, y = 704, width = 182, height = 164 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0005",
				spriteColorRect = { x = 180, y = 75, width = 182, height = 164 },
				textureRect = { x = 544, y = 708, width = 182, height = 164 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0006",
				spriteColorRect = { x = 180, y = 75, width = 182, height = 164 },
				textureRect = { x = 1096, y = 562, width = 182, height = 164 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0007",
				spriteColorRect = { x = 180, y = 75, width = 182, height = 164 },
				textureRect = { x = 912, y = 544, width = 182, height = 164 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0008",
				spriteColorRect = { x = 180, y = 75, width = 182, height = 164 },
				textureRect = { x = 728, y = 538, width = 182, height = 164 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0009",
				spriteColorRect = { x = 180, y = 75, width = 182, height = 164 },
				textureRect = { x = 544, y = 542, width = 182, height = 164 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Land_0010",
				spriteColorRect = { x = 180, y = 75, width = 182, height = 164 },
				textureRect = { x = 382, y = 1412, width = 182, height = 164 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0000",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 930, y = 394, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0001",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 742, y = 388, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0002",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 1122, y = 266, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0003",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 516, y = 392, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Fat_Run_0004",
				spriteColorRect = { x = 203, y = 91, width = 186, height = 148 },
				textureRect = { x = 934, y = 244, width = 186, height = 148 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0000",
				spriteColorRect = { x = 230, y = 73, width = 92, height = 166 },
				textureRect = { x = 860, y = 1336, width = 92, height = 166 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0001",
				spriteColorRect = { x = 236, y = 33, width = 92, height = 206 },
				textureRect = { x = 110, y = 1394, width = 92, height = 206 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0002",
				spriteColorRect = { x = 230, y = 21, width = 108, height = 218 },
				textureRect = { x = 406, y = 312, width = 108, height = 218 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0003",
				spriteColorRect = { x = 230, y = 19, width = 106, height = 220 },
				textureRect = { x = 2, y = 1394, width = 106, height = 220 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0004",
				spriteColorRect = { x = 230, y = 21, width = 106, height = 218 },
				textureRect = { x = 2, y = 1616, width = 106, height = 218 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0005",
				spriteColorRect = { x = 230, y = 51, width = 106, height = 188 },
				textureRect = { x = 110, y = 1602, width = 106, height = 188 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Jump_0006",
				spriteColorRect = { x = 230, y = 93, width = 106, height = 146 },
				textureRect = { x = 802, y = 1754, width = 106, height = 146 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Run_0000",
				spriteColorRect = { x = 230, y = 133, width = 98, height = 106 },
				textureRect = { x = 1344, y = 1356, width = 98, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Run_0001",
				spriteColorRect = { x = 230, y = 133, width = 98, height = 106 },
				textureRect = { x = 1244, y = 1356, width = 98, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Run_0002",
				spriteColorRect = { x = 230, y = 133, width = 98, height = 106 },
				textureRect = { x = 860, y = 1504, width = 98, height = 106 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Run_Land_0000",
				spriteColorRect = { x = 223, y = 139, width = 116, height = 100 },
				textureRect = { x = 516, y = 1946, width = 116, height = 100 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Run_Land_0001",
				spriteColorRect = { x = 223, y = 139, width = 116, height = 100 },
				textureRect = { x = 398, y = 1946, width = 116, height = 100 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0000",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 1154, y = 1736, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0001",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 1032, y = 1736, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0002",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 1138, y = 1594, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0003",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 1016, y = 1594, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0004",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 960, y = 1442, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0005",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 960, y = 1896, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0006",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 972, y = 1274, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0007",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 972, y = 1132, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0008",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 962, y = 990, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0009",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 910, y = 1754, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0010",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 894, y = 1612, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0011",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 772, y = 1612, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spin_0012",
				spriteColorRect = { x = 214, y = 99, width = 120, height = 140 },
				textureRect = { x = 956, y = 848, width = 120, height = 140 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spit_0000",
				spriteColorRect = { x = 210, y = 119, width = 164, height = 120 },
				textureRect = { x = 1094, y = 1110, width = 164, height = 120 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spit_0001",
				spriteColorRect = { x = 210, y = 119, width = 164, height = 120 },
				textureRect = { x = 1084, y = 988, width = 164, height = 120 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "toad_animations/Spit_0002",
				spriteColorRect = { x = 210, y = 119, width = 164, height = 120 },
				textureRect = { x = 1078, y = 866, width = 164, height = 120 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

