-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:6e781974ae937fd911d33812c146625c:f5cfecc5448df9781d9b102c9baf877a:a36d9826470a9a9591762a271dc2165d$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "alienBeige.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 132 },
				textureRect = { x = 914, y = 576, width = 80, height = 132 },
				spriteSourceSize = { width = 80, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alienBlue.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 132 },
				textureRect = { x = 886, y = 226, width = 80, height = 132 },
				spriteSourceSize = { width = 80, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alienGreen.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 132 },
				textureRect = { x = 982, y = 878, width = 80, height = 132 },
				spriteSourceSize = { width = 80, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alienPink.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 132 },
				textureRect = { x = 900, y = 878, width = 80, height = 132 },
				spriteSourceSize = { width = 80, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alienYellow.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 120 },
				textureRect = { x = 988, y = 710, width = 80, height = 120 },
				spriteSourceSize = { width = 80, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushAutumn.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 758, y = 812, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushDirt.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 758, y = 770, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushGrass.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 758, y = 728, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushMagic.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 758, y = 686, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushSand.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 758, y = 644, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushSnow.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 758, y = 602, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerBlue.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 962, y = 2, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerGreen.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 964, y = 854, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerRed.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 938, y = 854, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerWhite.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 902, y = 810, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerYellow.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 902, y = 786, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillAutumn.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 802, y = 860, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillDirt.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 790, y = 834, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillGrass.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 734, y = 868, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillMagic.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 666, y = 868, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillSand.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 598, y = 868, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillSnow.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 530, y = 868, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineAutumn_high.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 198 },
				textureRect = { x = 836, y = 2, width = 60, height = 198 },
				spriteSourceSize = { width = 60, height = 198 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineAutumn_low.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 158 },
				textureRect = { x = 1062, y = 520, width = 60, height = 158 },
				spriteSourceSize = { width = 60, height = 158 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineAutumn_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 202 },
				textureRect = { x = 988, y = 2, width = 60, height = 202 },
				spriteSourceSize = { width = 60, height = 202 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineBlue_high.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 198 },
				textureRect = { x = 774, y = 2, width = 60, height = 198 },
				spriteSourceSize = { width = 60, height = 198 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineBlue_low.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 158 },
				textureRect = { x = 1006, y = 360, width = 60, height = 158 },
				spriteSourceSize = { width = 60, height = 158 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineBlue_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 202 },
				textureRect = { x = 1126, y = 2, width = 60, height = 202 },
				spriteSourceSize = { width = 60, height = 202 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineGreen_high.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 198 },
				textureRect = { x = 914, y = 26, width = 60, height = 198 },
				spriteSourceSize = { width = 60, height = 198 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineGreen_low.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 158 },
				textureRect = { x = 1064, y = 832, width = 60, height = 158 },
				spriteSourceSize = { width = 60, height = 158 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineGreen_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 202 },
				textureRect = { x = 1064, y = 2, width = 60, height = 202 },
				spriteSourceSize = { width = 60, height = 202 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rockDirt.png",
				spriteColorRect = { x = 10, y = 0, width = 110, height = 124 },
				textureRect = { x = 662, y = 128, width = 110, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockDirt_moss1.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 644, y = 742, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockDirt_moss2.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 644, y = 616, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockDirt_moss3.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 644, y = 490, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockSnow_1.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 562, y = 894, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockSnow_2.png",
				spriteColorRect = { x = 10, y = 0, width = 110, height = 124 },
				textureRect = { x = 662, y = 2, width = 110, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockSnow_3.png",
				spriteColorRect = { x = 10, y = 0, width = 110, height = 124 },
				textureRect = { x = 788, y = 894, width = 110, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockStone.png",
				spriteColorRect = { x = 10, y = 0, width = 110, height = 124 },
				textureRect = { x = 676, y = 894, width = 110, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockStone_moss1.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 530, y = 742, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockStone_moss2.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 530, y = 616, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockStone_moss3.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 530, y = 490, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smallRockDirt.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 66 },
				textureRect = { x = 834, y = 418, width = 58, height = 66 },
				spriteSourceSize = { width = 58, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "smallRockGrass.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 66 },
				textureRect = { x = 774, y = 418, width = 58, height = 66 },
				spriteSourceSize = { width = 58, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "smallRockSnow.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 66 },
				textureRect = { x = 928, y = 786, width = 58, height = 66 },
				spriteSourceSize = { width = 58, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "smallRockStone.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 66 },
				textureRect = { x = 902, y = 718, width = 58, height = 66 },
				spriteSourceSize = { width = 58, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileAutumn.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 530, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileAutumn_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 398, y = 722, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileAutumn_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 790, y = 718, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileDirt.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 398, y = 542, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileDirt_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 398, y = 362, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileDirt_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 802, y = 602, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileGrass.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 398, y = 182, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileGrass_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 398, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileGrass_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 758, y = 486, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileLava.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 266, y = 722, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileLava_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 266, y = 542, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileLava_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 662, y = 370, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileMagic.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 266, y = 362, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileMagic_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 266, y = 182, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileMagic_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 662, y = 254, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileRock.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 266, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileRock_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 134, y = 722, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileRock_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 450, y = 902, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileSand.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 134, y = 542, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileSand_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 134, y = 362, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileSand_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 338, y = 902, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileSnow.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 134, y = 182, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileSnow_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 134, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileSnow_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 226, y = 902, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileStone.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 2, y = 722, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileStone_bridge.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 152 },
				textureRect = { x = 530, y = 336, width = 130, height = 152 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileStone_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 2, y = 542, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileStone_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 114, y = 902, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileWater.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 2, y = 362, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileWater_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 2, y = 182, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileWater_shadow.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 2, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileWater_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 2, y = 902, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileWood_bridge.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 152 },
				textureRect = { x = 530, y = 182, width = 130, height = 152 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "treeAutumn_high.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 950, y = 360, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeAutumn_low.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 174 },
				textureRect = { x = 1130, y = 598, width = 54, height = 174 },
				spriteSourceSize = { width = 54, height = 174 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeAutumn_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 1070, y = 206, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeBlue_high.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 1126, y = 206, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeBlue_low.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 174 },
				textureRect = { x = 1124, y = 422, width = 54, height = 174 },
				spriteSourceSize = { width = 54, height = 174 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeBlue_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 894, y = 360, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeCactus_1.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 132 },
				textureRect = { x = 996, y = 576, width = 64, height = 132 },
				spriteSourceSize = { width = 64, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeCactus_2.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 132 },
				textureRect = { x = 1070, y = 680, width = 58, height = 132 },
				spriteSourceSize = { width = 58, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeCactus_3.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 132 },
				textureRect = { x = 968, y = 226, width = 64, height = 132 },
				spriteSourceSize = { width = 64, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeGreen_high.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 830, y = 202, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeGreen_low.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 174 },
				textureRect = { x = 1126, y = 814, width = 54, height = 174 },
				spriteSourceSize = { width = 54, height = 174 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeGreen_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 774, y = 202, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "waveLava.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 20 },
				textureRect = { x = 870, y = 856, width = 66, height = 20 },
				spriteSourceSize = { width = 66, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "waveWater.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 20 },
				textureRect = { x = 858, y = 834, width = 66, height = 20 },
				spriteSourceSize = { width = 66, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

