-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:b63a77d0bed078080fa6f6932d52ca32:a978548d445ff2d4fb5d2f2e1b2df365:a36d9826470a9a9591762a271dc2165d$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "Explosion001.png",
				spriteColorRect = { x = 96, y = 86, width = 154, height = 214 },
				textureRect = { x = 510, y = 2, width = 154, height = 214 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion002.png",
				spriteColorRect = { x = 106, y = 104, width = 112, height = 198 },
				textureRect = { x = 250, y = 426, width = 112, height = 198 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion003.png",
				spriteColorRect = { x = 110, y = 138, width = 102, height = 162 },
				textureRect = { x = 1476, y = 182, width = 102, height = 162 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion004.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion005.png",
				spriteColorRect = { x = 52, y = 202, width = 242, height = 98 },
				textureRect = { x = 864, y = 2, width = 242, height = 98 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion006.png",
				spriteColorRect = { x = 58, y = 140, width = 196, height = 156 },
				textureRect = { x = 666, y = 2, width = 196, height = 156 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion007.png",
				spriteColorRect = { x = 36, y = 100, width = 246, height = 198 },
				textureRect = { x = 2, y = 426, width = 246, height = 198 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion008.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion009.png",
				spriteColorRect = { x = 28, y = 88, width = 250, height = 210 },
				textureRect = { x = 2, y = 214, width = 250, height = 210 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion010.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion011.png",
				spriteColorRect = { x = 34, y = 90, width = 248, height = 204 },
				textureRect = { x = 260, y = 2, width = 248, height = 204 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion012.png",
				spriteColorRect = { x = 30, y = 82, width = 256, height = 210 },
				textureRect = { x = 2, y = 2, width = 256, height = 210 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion013.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion014.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion015.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion016.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion017.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion018.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion019.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion020.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion021.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion022.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion023.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion024.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion025.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Explosion026.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				textureRect = { x = 260, y = 208, width = 1, height = 1 },
				spriteSourceSize = { width = 314, height = 312 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "alienBeige.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 132 },
				textureRect = { x = 1824, y = 512, width = 80, height = 132 },
				spriteSourceSize = { width = 80, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alienBlue.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 132 },
				textureRect = { x = 1742, y = 524, width = 80, height = 132 },
				spriteSourceSize = { width = 80, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alienGreen.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 132 },
				textureRect = { x = 1422, y = 362, width = 80, height = 132 },
				spriteSourceSize = { width = 80, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alienPink.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 132 },
				textureRect = { x = 1922, y = 182, width = 80, height = 132 },
				spriteSourceSize = { width = 80, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "alienYellow.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 120 },
				textureRect = { x = 892, y = 658, width = 80, height = 120 },
				spriteSourceSize = { width = 80, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushAutumn.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 1976, y = 442, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushDirt.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 1976, y = 400, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushGrass.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 1976, y = 358, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushMagic.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 1976, y = 316, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushSand.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 1736, y = 726, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bushSnow.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 40 },
				textureRect = { x = 734, y = 160, width = 30, height = 40 },
				spriteSourceSize = { width = 30, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerBlue.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 1078, y = 756, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerGreen.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 1052, y = 756, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerRed.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 1026, y = 756, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerWhite.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 1000, y = 756, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flowerYellow.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 22 },
				textureRect = { x = 974, y = 756, width = 24, height = 22 },
				spriteSourceSize = { width = 24, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillAutumn.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 1042, y = 730, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillDirt.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 974, y = 730, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillGrass.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 666, y = 186, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillMagic.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 1906, y = 600, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillSand.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 666, y = 160, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hillSnow.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 24 },
				textureRect = { x = 266, y = 752, width = 66, height = 24 },
				spriteSourceSize = { width = 66, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineAutumn_high.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 198 },
				textureRect = { x = 1566, y = 346, width = 60, height = 198 },
				spriteSourceSize = { width = 60, height = 198 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineAutumn_low.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 158 },
				textureRect = { x = 1914, y = 316, width = 60, height = 158 },
				spriteSourceSize = { width = 60, height = 158 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineAutumn_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 202 },
				textureRect = { x = 1796, y = 308, width = 60, height = 202 },
				spriteSourceSize = { width = 60, height = 202 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineBlue_high.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 198 },
				textureRect = { x = 1018, y = 102, width = 60, height = 198 },
				spriteSourceSize = { width = 60, height = 198 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineBlue_low.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 158 },
				textureRect = { x = 1504, y = 346, width = 60, height = 158 },
				spriteSourceSize = { width = 60, height = 158 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineBlue_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 202 },
				textureRect = { x = 830, y = 574, width = 60, height = 202 },
				spriteSourceSize = { width = 60, height = 202 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineGreen_high.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 198 },
				textureRect = { x = 448, y = 208, width = 60, height = 198 },
				spriteSourceSize = { width = 60, height = 198 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineGreen_low.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 158 },
				textureRect = { x = 1018, y = 302, width = 60, height = 158 },
				spriteSourceSize = { width = 60, height = 158 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pineGreen_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 202 },
				textureRect = { x = 254, y = 214, width = 60, height = 202 },
				spriteSourceSize = { width = 60, height = 202 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rockDirt.png",
				spriteColorRect = { x = 10, y = 0, width = 110, height = 124 },
				textureRect = { x = 1176, y = 488, width = 110, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockDirt_moss1.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 1628, y = 524, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockDirt_moss2.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 1308, y = 362, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockDirt_moss3.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 1194, y = 362, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockSnow_1.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 1080, y = 362, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockSnow_2.png",
				spriteColorRect = { x = 10, y = 0, width = 110, height = 124 },
				textureRect = { x = 1064, y = 488, width = 110, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockSnow_3.png",
				spriteColorRect = { x = 10, y = 0, width = 110, height = 124 },
				textureRect = { x = 892, y = 462, width = 110, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockStone.png",
				spriteColorRect = { x = 10, y = 0, width = 110, height = 124 },
				textureRect = { x = 266, y = 626, width = 110, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockStone_moss1.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 1808, y = 182, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockStone_moss2.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 1694, y = 182, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rockStone_moss3.png",
				spriteColorRect = { x = 8, y = 0, width = 112, height = 124 },
				textureRect = { x = 1580, y = 182, width = 112, height = 124 },
				spriteSourceSize = { width = 130, height = 182 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smallRockDirt.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 66 },
				textureRect = { x = 1198, y = 682, width = 58, height = 66 },
				spriteSourceSize = { width = 58, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "smallRockGrass.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 66 },
				textureRect = { x = 1198, y = 614, width = 58, height = 66 },
				spriteSourceSize = { width = 58, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "smallRockSnow.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 66 },
				textureRect = { x = 1736, y = 658, width = 58, height = 66 },
				spriteSourceSize = { width = 58, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "smallRockStone.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 66 },
				textureRect = { x = 892, y = 588, width = 58, height = 66 },
				spriteSourceSize = { width = 58, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileAutumn.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1344, y = 182, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileAutumn_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1212, y = 182, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileAutumn_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1086, y = 614, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileDirt.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1080, y = 182, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileDirt_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 886, y = 282, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileDirt_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 974, y = 614, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileGrass.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 886, y = 102, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileGrass_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 698, y = 578, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileGrass_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1906, y = 484, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileLava.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 566, y = 578, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileLava_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 434, y = 588, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileLava_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1624, y = 650, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileMagic.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 684, y = 398, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileMagic_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 642, y = 218, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileMagic_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1512, y = 662, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileRock.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 552, y = 398, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileRock_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 420, y = 408, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileRock_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1512, y = 546, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileSand.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 510, y = 218, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileSand_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 316, y = 208, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileSand_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1400, y = 622, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileSnow.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1900, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileSnow_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1768, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileSnow_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1400, y = 506, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileStone.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1636, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileStone_bridge.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 152 },
				textureRect = { x = 134, y = 626, width = 130, height = 152 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileStone_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1504, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileStone_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1288, y = 604, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileWater.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1372, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileWater_full.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1240, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileWater_shadow.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 178 },
				textureRect = { x = 1108, y = 2, width = 130, height = 178 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tileWater_tile.png",
				spriteColorRect = { x = 10, y = 10, width = 110, height = 114 },
				textureRect = { x = 1288, y = 488, width = 110, height = 114 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "tileWood_bridge.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 152 },
				textureRect = { x = 2, y = 626, width = 130, height = 152 },
				spriteSourceSize = { width = 130, height = 178 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "treeAutumn_high.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 1740, y = 308, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeAutumn_low.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 174 },
				textureRect = { x = 1858, y = 308, width = 54, height = 174 },
				spriteSourceSize = { width = 54, height = 174 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeAutumn_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 1684, y = 308, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeBlue_high.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 1628, y = 308, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeBlue_low.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 174 },
				textureRect = { x = 816, y = 398, width = 54, height = 174 },
				spriteSourceSize = { width = 54, height = 174 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeBlue_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 830, y = 160, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeCactus_1.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 132 },
				textureRect = { x = 1890, y = 646, width = 64, height = 132 },
				spriteSourceSize = { width = 64, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeCactus_2.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 132 },
				textureRect = { x = 1004, y = 462, width = 58, height = 132 },
				spriteSourceSize = { width = 58, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeCactus_3.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 132 },
				textureRect = { x = 1824, y = 646, width = 64, height = 132 },
				spriteSourceSize = { width = 64, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeGreen_high.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 774, y = 182, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeGreen_low.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 174 },
				textureRect = { x = 378, y = 604, width = 54, height = 174 },
				spriteSourceSize = { width = 54, height = 174 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "treeGreen_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 214 },
				textureRect = { x = 364, y = 388, width = 54, height = 214 },
				spriteSourceSize = { width = 54, height = 214 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "waveLava.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 20 },
				textureRect = { x = 634, y = 758, width = 66, height = 20 },
				spriteSourceSize = { width = 66, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "waveWater.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 20 },
				textureRect = { x = 566, y = 758, width = 66, height = 20 },
				spriteSourceSize = { width = 66, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

