-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:6465ddbeabb2bf10de56a3dc7ddc9ece:e7a5463468625c2470d66faea4763058:92dfd80bd07bfbd9de640af171064e90$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "poprocks/P1_0000",
				spriteColorRect = { x = 240, y = 209, width = 180, height = 232 },
				textureRect = { x = 1160, y = 534, width = 180, height = 232 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P1_0001",
				spriteColorRect = { x = 240, y = 209, width = 180, height = 232 },
				textureRect = { x = 978, y = 582, width = 180, height = 232 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P1_0002",
				spriteColorRect = { x = 177, y = 134, width = 272, height = 304 },
				textureRect = { x = 2, y = 628, width = 272, height = 304 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P1_0003",
				spriteColorRect = { x = 210, y = 164, width = 240, height = 276 },
				textureRect = { x = 870, y = 304, width = 240, height = 276 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P1_0004",
				spriteColorRect = { x = 233, y = 230, width = 202, height = 210 },
				textureRect = { x = 774, y = 582, width = 202, height = 210 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P2_0000",
				spriteColorRect = { x = 238, y = 208, width = 164, height = 230 },
				textureRect = { x = 442, y = 792, width = 164, height = 230 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P2_0001",
				spriteColorRect = { x = 238, y = 208, width = 164, height = 230 },
				textureRect = { x = 276, y = 792, width = 164, height = 230 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P2_0002",
				spriteColorRect = { x = 178, y = 153, width = 268, height = 292 },
				textureRect = { x = 954, y = 2, width = 268, height = 292 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P2_0003",
				spriteColorRect = { x = 202, y = 170, width = 256, height = 278 },
				textureRect = { x = 314, y = 296, width = 256, height = 278 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P2_0004",
				spriteColorRect = { x = 222, y = 236, width = 218, height = 214 },
				textureRect = { x = 554, y = 576, width = 218, height = 214 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P3_0000",
				spriteColorRect = { x = 248, y = 208, width = 156, height = 228 },
				textureRect = { x = 766, y = 794, width = 156, height = 228 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P3_0001",
				spriteColorRect = { x = 248, y = 208, width = 156, height = 228 },
				textureRect = { x = 608, y = 792, width = 156, height = 228 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P3_0002",
				spriteColorRect = { x = 181, y = 114, width = 310, height = 330 },
				textureRect = { x = 2, y = 296, width = 310, height = 330 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P3_0003",
				spriteColorRect = { x = 206, y = 147, width = 270, height = 300 },
				textureRect = { x = 682, y = 2, width = 270, height = 300 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P3_0004",
				spriteColorRect = { x = 221, y = 235, width = 238, height = 214 },
				textureRect = { x = 314, y = 576, width = 238, height = 214 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P4_0000",
				spriteColorRect = { x = 240, y = 202, width = 178, height = 236 },
				textureRect = { x = 1160, y = 768, width = 178, height = 236 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P4_0001",
				spriteColorRect = { x = 240, y = 202, width = 178, height = 236 },
				textureRect = { x = 1112, y = 296, width = 178, height = 236 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P4_0002",
				spriteColorRect = { x = 153, y = 157, width = 352, height = 292 },
				textureRect = { x = 2, y = 2, width = 352, height = 292 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P4_0003",
				spriteColorRect = { x = 167, y = 172, width = 324, height = 286 },
				textureRect = { x = 356, y = 2, width = 324, height = 286 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "poprocks/P4_0004",
				spriteColorRect = { x = 172, y = 223, width = 296, height = 236 },
				textureRect = { x = 572, y = 304, width = 296, height = 236 },
				spriteSourceSize = { width = 620, height = 620 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

